---
abstract: 'A simple but extensible Perl dist tester.'
author:
  - 'Thibaut Le Page <thilp@cpan.org>'
build_requires:
  File::Temp: '0'
  IPC::System::Simple: '0'
  Module::Build: '0.3601'
  Test::Compile: '0'
  Test::Modern: '0'
  Test::More: '0.88'
  autodie: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mistress
no_index:
  directory:
    - t
    - xt
    - examples
  package:
    - DB
provides:
  Mistress:
    file: lib/Mistress.pm
    version: '0.001'
  Mistress::App:
    file: lib/Mistress/App.pm
    version: '0.001'
  Mistress::App::Command:
    file: lib/Mistress/App/Command.pm
    version: '0.001'
  Mistress::App::Command::consider:
    file: lib/Mistress/App/Command/consider.pm
    version: '0.001'
  Mistress::App::Command::lol:
    file: lib/Mistress/App/Command/lol.pm
    version: '0.001'
  Mistress::App::Command::report:
    file: lib/Mistress/App/Command/report.pm
    version: '0.001'
  Mistress::App::Command::smoke:
    file: lib/Mistress/App/Command/smoke.pm
    version: '0.001'
  Mistress::Env:
    file: lib/Mistress/Env.pm
    version: '0.001'
  Mistress::Env::Config:
    file: lib/Mistress/Env/Config.pm
    version: '0.001'
  Mistress::Env::Config::File:
    file: lib/Mistress/Env/Config/File.pm
    version: '0.001'
  Mistress::Env::Config::Hash:
    file: lib/Mistress/Env/Config/Hash.pm
    version: '0.001'
  Mistress::Env::Fs:
    file: lib/Mistress/Env/Fs.pm
    version: '0.001'
  Mistress::Env::Fs::Disk:
    file: lib/Mistress/Env/Fs/Disk.pm
    version: '0.001'
  Mistress::Obj::Dist:
    file: lib/Mistress/Obj/Dist.pm
    version: '0.001'
  Mistress::Obj::DistSet:
    file: lib/Mistress/Obj/DistSet.pm
    version: '0.001'
  Mistress::Obj::PerlInterpreter:
    file: lib/Mistress/Obj/PerlInterpreter.pm
    version: '0.001'
  Mistress::Obj::PerlLib:
    file: lib/Mistress/Obj/PerlLib.pm
    version: '0.001'
  Mistress::Obj::Report:
    file: lib/Mistress/Obj/Report.pm
    version: '0.001'
  Mistress::Plugin::UploadGatherer:
    file: lib/Mistress/Plugin/UploadGatherer.pm
    version: '0.001'
  Mistress::Role::DistGatherer:
    file: lib/Mistress/Role/DistGatherer.pm
    version: '0.001'
  Mistress::Role::HasPlugins:
    file: lib/Mistress/Role/HasPlugins.pm
    version: '0.001'
  Mistress::Util:
    file: lib/Mistress/Util.pm
    version: '0.001'
requires:
  App::Cmd::Setup: '0.309'
  Carp: '0'
  Class::Load: '0'
  Clone: '0'
  Data::Dump: '0'
  Digest::MD5: '0'
  Exporter: '0'
  List::Util: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0'
  Module::Pluggable: '0'
  Moo: '0'
  Moo::Role: '0'
  MooX::Types::MooseLike::Base: '0'
  Package::Stash: '0'
  Path::Class: '0'
  Safe::Isa: '0'
  Sereal::Decoder: '0'
  Sereal::Encoder: '0'
  Try::Tiny: '0'
  YAML::XS: '0.35'
  namespace::clean: '0'
  parent: '0'
  perl: '5.012'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/thilp/Mistress/issues
  homepage: https://github.com/thilp/Mistress
  repository: https://github.com/thilp/Mistress.git
version: '0.001'
